# Generated by Django 4.2.3 on 2023-07-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authsystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='cretatedAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
